spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
  datasource:
        name: test
        url: jdbc:mysql://localhost/library?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: wqeq
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.lcdzzz.managebooks.pojo
  configuration:
    map-underscore-to-camel-case: true
